"""add roles table

Revision ID: 23b2a6982d1c
Revises: move_connection_to_sync_jobs
Create Date: 2026-03-25 07:55:04.679509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '23b2a6982d1c'
down_revision: Union[str, None] = 'move_connection_to_sync_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)

    # Seed system roles
    import uuid
    import json
    from datetime import datetime, timezone

    # Define permissions for each role
    resources = ["products", "categories", "media", "brands", "channels", "suppliers", "sync", "quality", "i18n", "users", "settings"]

    admin_perms = {res: "write" for res in resources}
    editor_perms = {
        "products": "write",
        "categories": "write",
        "media": "write",
        "brands": "write",
        "channels": "write",
        "suppliers": "write",
        "sync": "write",
        "quality": "write",
        "i18n": "write",
        "users": "read",
        "settings": "read",
    }
    viewer_perms = {res: "read" for res in resources}

    now = datetime.now(timezone.utc)

    roles_data = [
        {
            'id': str(uuid.uuid4()),
            'name': 'admin',
            'description': 'Administrador del sistema con acceso completo',
            'permissions': json.dumps(admin_perms),
            'is_system': 1,
            'is_active': 1,
            'created_at': now,
            'updated_at': now,
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'editor',
            'description': 'Editor con permisos de escritura en recursos principales',
            'permissions': json.dumps(editor_perms),
            'is_system': 1,
            'is_active': 1,
            'created_at': now,
            'updated_at': now,
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'viewer',
            'description': 'Visor con permisos de solo lectura',
            'permissions': json.dumps(viewer_perms),
            'is_system': 1,
            'is_active': 1,
            'created_at': now,
            'updated_at': now,
        },
    ]

    op.bulk_insert(
        sa.table('roles',
            sa.column('id', sa.String),
            sa.column('name', sa.String),
            sa.column('description', sa.Text),
            sa.column('permissions', sa.JSON),
            sa.column('is_system', sa.Boolean),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        roles_data
    )

    # Note: SQLite has limited ALTER TABLE support, skipping column alterations
    # op.drop_column('channels', 'connection_config')  # Already done in previous migration
    # op.drop_column('channels', 'connection_type')  # Already done in previous migration
    # op.alter_column('export_preferences', ...)  # SQLite doesn't support ALTER COLUMN TYPE
    # op.drop_constraint / op.create_foreign_key  # Product comments FK
    # op.add_column('saved_views', 'is_public')  # Will be added separately if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # Note: SQLite limitations - other changes skipped
    # ### end Alembic commands ###
