"""add_product_sync_history_and_sync_job_scheduling

Revision ID: 48479dbab2a4
Revises: f78fa7467002
Create Date: 2026-03-11 18:32:38.739551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48479dbab2a4'
down_revision: Union[str, None] = 'f78fa7467002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sync_history',
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sync_history_channel'), 'product_sync_history', ['channel'], unique=False)
    op.create_index(op.f('ix_product_sync_history_job_id'), 'product_sync_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_product_sync_history_sku'), 'product_sync_history', ['sku'], unique=False)
    op.add_column('sync_jobs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sync_jobs', sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False))
    op.add_column('sync_jobs', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.add_column('sync_jobs', sa.Column('scheduled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('sync_jobs', sa.Column('cron_expression', sa.String(length=100), nullable=True))
    op.add_column('sync_jobs', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_jobs', 'next_run_at')
    op.drop_column('sync_jobs', 'cron_expression')
    op.drop_column('sync_jobs', 'scheduled')
    op.drop_column('sync_jobs', 'next_retry_at')
    op.drop_column('sync_jobs', 'max_retries')
    op.drop_column('sync_jobs', 'retry_count')
    op.drop_index(op.f('ix_product_sync_history_sku'), table_name='product_sync_history')
    op.drop_index(op.f('ix_product_sync_history_job_id'), table_name='product_sync_history')
    op.drop_index(op.f('ix_product_sync_history_channel'), table_name='product_sync_history')
    op.drop_table('product_sync_history')
    # ### end Alembic commands ###
