"""Add PIM field mapping configuration

Revision ID: 8c49d6b53752
Revises: 23b2a6982d1c
Create Date: 2026-03-25 22:08:53.023976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c49d6b53752'
down_revision: Union[str, None] = '23b2a6982d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create pim_resource_mappings table
    op.create_table('pim_resource_mappings',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('resource', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('mappings', sa.JSON(), nullable=False),
        sa.Column('defaults', sa.JSON(), nullable=False),
        sa.Column('transform_config', sa.JSON(), nullable=False),
        sa.Column('created_by', sa.String(length=255), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('resource', name='uq_pim_resource')
    )
    op.create_index(op.f('ix_pim_resource_mappings_resource'), 'pim_resource_mappings', ['resource'], unique=False)

    # Add saved_views.is_public column (if not exists)
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    op.drop_index(op.f('ix_pim_resource_mappings_resource'), table_name='pim_resource_mappings')
    op.drop_table('pim_resource_mappings')
    # ### end Alembic commands ###
