"""fix media foreign key

Revision ID: f78fa7467002
Revises: 
Create Date: 2026-02-13 19:37:38.897014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78fa7467002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets') as batch_op:
        batch_op.create_foreign_key('fk_media_assets_sku', 'products', ['sku'], ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets') as batch_op:
        batch_op.drop_constraint('fk_media_assets_sku', type_='foreignkey')
    # ### end Alembic commands ###
